# 基于nginx镜像，构建一个新的镜像（本质就是从docker仓库拉取一个nginx镜像）
FROM nginx:1.19.0

# 替换配置文件
COPY ./nginx.conf /etc/nginx/nginx.conf
# 替换配置文件
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# 拷贝静态资源文件到root目录
COPY . /usr/share/nginx/html